fix fedora bootloader update

diff --git a/files/ald b/files/ald
--- a/files/ald
+++ b/files/ald
@@ -120,6 +120,7 @@ fail_ex() {
         pprint "Attempting cleanup..."
         podman rm ald-tmp &>/dev/null
         podman rm ald-utils &>/dev/null
+        podman rm ald-boot &>/dev/null
         rm -rf "${ALD_PATH:?}/${1:?}"
         chattr -f -i "${ALD_PATH:?}/init/$1.sh"
         rm -rf "${ALD_PATH:?}/init/${1:?}.sh"
@@ -396,20 +397,16 @@ update_bootloader() {
 }
 
 fedora_grub() {
-    podman run -ti --name ald-boot "$SOURCE_IMAGE" << "    EOF"
-        mkdir -p /boot/efi/EFI
-        (((dnf reinstall -y grub2-efi-x64.x86_64 ||
-            dnf install -y grub2-efi-x64.x86_64) ||
-            dnf5 reinstall -y grub2-efi-x64.x86_64) ||
-            dnf5 install -y grub2-efi-x64.x86_64) ||
-            (echo "Couldn't install grub!" && exit 1)
-        (((dnf reinstall -y shim-x64.x86_64 ||
-            dnf install -y shim-x64.x86_64) ||
-            dnf5 reinstall -y shim-x64.x86_64) ||
-            dnf5 install -y shim-x64.x86_64) ||
-            (echo "Couldn't install shim!" && exit 1)
-        exit 0
-    EOF
+    mkdir "${ALD_PATH:?}/tmp-boot"
+    cat > "${ALD_PATH:?}/tmp-boot/Containerfile" << EOF
+FROM "${SOURCE_IMAGE}"
+
+RUN (sudo dnf5 reinstall -y grub2-efi-x64.x86_64 || sudo dnf5 install -y grub2-efi-x64.x86_64) || (echo "Couldn't install grub!" && exit 1)
+
+RUN (dnf5 reinstall -y shim-x64.x86_64 || sudo dnf5 install -y shim-x64.x86_64) || (echo "Couldn't install shim!" && exit 1)
+EOF
+    podman build -t localhost/ald-boot "${ALD_PATH:?}/tmp-boot" || fail_ex "-1" "Couldn't create image."
+    podman create --name ald-boot localhost/ald-boot &>/dev/null || fail_ex "-1" "Couldn't sync files."
 
     if [[ "$?" != "0" ]]; then fail_ex "-1" "Failed to fetch bootloader components."; fi
     podman cp ald-boot:/boot/efi/EFI/fedora/shimx64.efi "${EFI_PATH:?}" ||
@@ -449,7 +446,9 @@ fedora_grub() {
     rm "${EFI_PATH:?}"/{grubx64.efi,mmx64.efi,BOOTX64.CSV,fbx64.efi} ||
         printf "Failed to cleanup bootloader components.\n"
 
-    podman rm ald-boot || printf "Failed to remove container ald-boot.\n"
+    podman rm ald-boot &>/dev/null || printf "Failed to remove container ald-boot.\n"
+    podman rmi localhost/ald-boot &>/dev/null || printf "Failed to remove image localhost/ald-boot.\n"
+    rm -rf "${ALD_PATH:?}/tmp-boot" &>/dev/null
     pprint "Update complete!\n"
 }
 
